name: Api run

on:
  workflow_dispatch:
    branches:
      - main

env:
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

jobs:
  start-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Start API
        run: |
          ngrok http -hostname=api.paperlock.tk 5000 --region us --log=stdout --authtoken $NGROK_AUTH_TOKEN > ngrok.log &
          sleep 5
          subdomain=$(grep -o "https://\(.*\)\.ngrok\.io" ngrok.log | sed "s/https:\/\/\(.*\)\.ngrok\.io/\1/g")
          cname="api.paperlock.tk"
          value="$subdomain.ngrok.io"
          echo "Creating CNAME record for $cname -> $value"
          echo "Add the following CNAME record to your DNS settings:"
          echo "$cname.  IN  CNAME  $value."
          python app.py --ngrok-url "https://$cname"

