name: Api run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-repository-name:latest

      - name: Deploy to Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: your-server-ip
          username: your-server-username
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /path/to/your/repository
            docker-compose pull
            docker-compose up -d
